const defaultColor = '#4a4a4a';

const mqttOptions = {
    keepalive: 10,
    protocolId: 'MQTT',
    protocolVersion: 4,
    clean: true,
    reconnectPeriod: 1000,
    connectTimeout: 30 * 1000
};

const config = {
    lamps: ['chloe', 'alex'],
    url: 'wss://lampify.duckdns.org/wss',
    topic: 'lampify/#',
    topics: {
        hex: 'lampify/hex',
        mode: 'lampify/mode',
        speed: 'lampify/speed',
        brightness: 'lampify/brightness',
    },
    modes: [
        'static',
        'blink',
        'breath',
        'color_wipe',
        'color_wipe_inv',
        'color_wipe_rev',
        'color_wipe_rev_inv',
        'color_wipe_random',
        'random_color',
        'single_dynamic',
        'multi_dynamic',
        'rainbow',
        'rainbow_cycle',
        'scan',
        'dual_scan',
        'fade',
        'theater_chase',
        'theater_chase_rainbow',
        'running_lights',
        'twinkle',
        'twinkle_random',
        'twinkle_fade',
        'twinkle_fade_random',
        'sparkle',
        'flash_sparkle',
        'hyper_sparkle',
        'strobe',
        'strobe_rainbow',
        'multi_strobe',
        'blink_rainbow',
        'chase_white',
        'chase_color',
        'chase_random',
        'chase_rainbow',
        'chase_flash',
        'chase_flash_random',
        'chase_rainbow_white',
        'chase_blackout',
        'chase_blackout_rainbow',
        'color_sweep_random',
        'running_color',
        'running_red_blue',
        'running_random',
        'larson_scanner',
        'comet',
        'fireworks',
        'fireworks_random',
        'merry_christmas',
        'halloween',
        'fire_flicker',
        'fire_flicker_soft',
        'fire_flicker_intense',
        'circus_combustus',
        'bicolor_chase',
        'tricolor_chase',
        'icu',
    ]
};

export {config, mqttOptions, defaultColor};